// Alceuri drankendatabase
// abv = alcoholpercentage (% vol), vol = standaard serveervolume in ml (gebruikt als de kaart geen volume vermeldt)
// cat wordt gebruikt voor fallback-schattingen en iconen
const DRINKS_DB = [
  // ── Pils & lagers ──────────────────────────────────────────────
  { name: "Jupiler", aliases: ["jupiler blue"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Stella Artois", aliases: ["stella"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Maes", aliases: ["maes pils"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Cristal", aliases: ["cristal alken"], abv: 5.0, vol: 250, cat: "bier" },
  { name: "Primus", aliases: ["primus haacht"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Bockor", aliases: [], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Heineken", aliases: [], abv: 5.0, vol: 250, cat: "bier" },
  { name: "Carlsberg", aliases: [], abv: 5.0, vol: 250, cat: "bier" },
  { name: "Corona", aliases: ["corona extra"], abv: 4.5, vol: 330, cat: "bier" },
  { name: "Desperados", aliases: [], abv: 5.9, vol: 330, cat: "bier" },
  { name: "Vedett", aliases: ["vedett extra blond"], abv: 5.2, vol: 330, cat: "bier" },
  { name: "Vedett IPA", aliases: ["vedett extra ipa"], abv: 5.5, vol: 330, cat: "bier" },

  // ── Speciaalbieren ─────────────────────────────────────────────
  { name: "Duvel", aliases: [], abv: 8.5, vol: 330, cat: "bier" },
  { name: "Duvel Tripel Hop", aliases: ["tripel hop"], abv: 9.5, vol: 330, cat: "bier" },
  { name: "Westmalle Dubbel", aliases: ["westmalle bruin"], abv: 7.0, vol: 330, cat: "bier" },
  { name: "Westmalle Tripel", aliases: ["westmalle"], abv: 9.5, vol: 330, cat: "bier" },
  { name: "Chimay Blauw", aliases: ["chimay bleue", "chimay blue", "chimay grande reserve"], abv: 9.0, vol: 330, cat: "bier" },
  { name: "Chimay Rood", aliases: ["chimay rouge", "chimay red"], abv: 7.0, vol: 330, cat: "bier" },
  { name: "Chimay Wit", aliases: ["chimay triple", "chimay tripel", "chimay blanche"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Chimay Goud", aliases: ["chimay doree"], abv: 4.8, vol: 330, cat: "bier" },
  { name: "Rochefort 6", aliases: [], abv: 7.5, vol: 330, cat: "bier" },
  { name: "Rochefort 8", aliases: [], abv: 9.2, vol: 330, cat: "bier" },
  { name: "Rochefort 10", aliases: [], abv: 11.3, vol: 330, cat: "bier" },
  { name: "Orval", aliases: [], abv: 6.2, vol: 330, cat: "bier" },
  { name: "Westvleteren 12", aliases: ["westvleteren"], abv: 10.2, vol: 330, cat: "bier" },
  { name: "St. Bernardus Abt 12", aliases: ["st bernardus", "sint bernardus", "abt 12"], abv: 10.0, vol: 330, cat: "bier" },
  { name: "St. Bernardus Tripel", aliases: ["sint bernardus tripel"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Tripel Karmeliet", aliases: ["karmeliet"], abv: 8.4, vol: 330, cat: "bier" },
  { name: "La Chouffe", aliases: ["chouffe", "la chouffe blond"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Mc Chouffe", aliases: ["mcchouffe"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Kwak", aliases: ["pauwel kwak"], abv: 8.4, vol: 330, cat: "bier" },
  { name: "Delirium Tremens", aliases: ["delirium"], abv: 8.5, vol: 330, cat: "bier" },
  { name: "Delirium Red", aliases: [], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Duchesse de Bourgogne", aliases: ["duchesse"], abv: 6.2, vol: 250, cat: "bier" },
  { name: "Leffe Blond", aliases: ["leffe"], abv: 6.6, vol: 330, cat: "bier" },
  { name: "Leffe Bruin", aliases: ["leffe brune", "leffe donker"], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Leffe Tripel", aliases: [], abv: 8.5, vol: 330, cat: "bier" },
  { name: "Leffe Ruby", aliases: [], abv: 5.0, vol: 330, cat: "bier" },
  { name: "Grimbergen Blond", aliases: ["grimbergen"], abv: 6.7, vol: 330, cat: "bier" },
  { name: "Grimbergen Dubbel", aliases: ["grimbergen bruin"], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Grimbergen Tripel", aliases: [], abv: 9.0, vol: 330, cat: "bier" },
  { name: "Affligem Blond", aliases: ["affligem"], abv: 6.7, vol: 330, cat: "bier" },
  { name: "Omer", aliases: ["omer traditional blond"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Cornet", aliases: ["cornet oaked"], abv: 8.5, vol: 330, cat: "bier" },
  { name: "Gulden Draak", aliases: [], abv: 10.5, vol: 330, cat: "bier" },
  { name: "Piraat", aliases: [], abv: 10.5, vol: 330, cat: "bier" },
  { name: "Straffe Hendrik Tripel", aliases: ["straffe hendrik"], abv: 9.0, vol: 330, cat: "bier" },
  { name: "Straffe Hendrik Quadrupel", aliases: [], abv: 11.0, vol: 330, cat: "bier" },
  { name: "Brugse Zot", aliases: ["zot"], abv: 6.0, vol: 330, cat: "bier" },
  { name: "Brugse Zot Dubbel", aliases: [], abv: 7.5, vol: 330, cat: "bier" },
  { name: "Kasteel Rouge", aliases: [], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Kasteel Donker", aliases: ["kasteel bruin"], abv: 11.0, vol: 330, cat: "bier" },
  { name: "Kasteel Tripel", aliases: [], abv: 11.0, vol: 330, cat: "bier" },
  { name: "Pater Lieven", aliases: [], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Augustijn", aliases: ["augustijn blond"], abv: 7.5, vol: 330, cat: "bier" },
  { name: "Ename Blond", aliases: ["ename"], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Ename Tripel", aliases: [], abv: 8.5, vol: 330, cat: "bier" },
  { name: "Maredsous Blond", aliases: ["maredsous 6"], abv: 6.0, vol: 330, cat: "bier" },
  { name: "Maredsous Tripel", aliases: ["maredsous 10"], abv: 10.0, vol: 330, cat: "bier" },
  { name: "Achel Blond", aliases: ["achel"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "La Trappe Tripel", aliases: ["la trappe"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "La Trappe Quadrupel", aliases: [], abv: 10.0, vol: 330, cat: "bier" },
  { name: "Pater", aliases: ["paterke"], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Barbar", aliases: ["barbar honingbier"], abv: 8.0, vol: 330, cat: "bier" },
  { name: "Bush Amber", aliases: ["bush"], abv: 12.0, vol: 330, cat: "bier" },

  // ── Wit / amber / fruit / zuur ────────────────────────────────
  { name: "Hoegaarden", aliases: ["hoegaarden wit"], abv: 4.9, vol: 250, cat: "bier" },
  { name: "Brugs Witbier", aliases: ["brugs"], abv: 4.8, vol: 250, cat: "bier" },
  { name: "Blanche de Namur", aliases: ["blanche"], abv: 4.5, vol: 250, cat: "bier" },
  { name: "St. Bernardus Witbier", aliases: [], abv: 5.5, vol: 250, cat: "bier" },
  { name: "Palm", aliases: ["palm speciale"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "De Koninck", aliases: ["bolleke", "koninck"], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Tongerlo Blond", aliases: ["tongerlo"], abv: 6.5, vol: 330, cat: "bier" },
  { name: "Kriek Lindemans", aliases: ["kriek"], abv: 3.5, vol: 250, cat: "bier" },
  { name: "Kriek Boon", aliases: [], abv: 4.0, vol: 250, cat: "bier" },
  { name: "Kriek St. Louis", aliases: ["st louis kriek"], abv: 3.2, vol: 250, cat: "bier" },
  { name: "Geuze Boon", aliases: ["geuze", "gueuze"], abv: 7.0, vol: 250, cat: "bier" },
  { name: "Oude Geuze 3 Fonteinen", aliases: ["3 fonteinen", "drie fonteinen"], abv: 6.0, vol: 375, cat: "bier" },
  { name: "Rodenbach", aliases: [], abv: 5.2, vol: 250, cat: "bier" },
  { name: "Rodenbach Grand Cru", aliases: [], abv: 6.0, vol: 330, cat: "bier" },
  { name: "Liefmans Fruitesse", aliases: ["liefmans", "fruitesse"], abv: 3.8, vol: 250, cat: "bier" },
  { name: "Mystic Kriek", aliases: ["mystic"], abv: 3.5, vol: 250, cat: "bier" },

  // ── Wijn & schuimwijn ─────────────────────────────────────────
  { name: "Witte wijn (glas)", aliases: ["witte wijn", "huiswijn wit", "wit", "vin blanc", "white wine", "glas witte wijn"], abv: 12.0, vol: 150, cat: "wijn" },
  { name: "Rode wijn (glas)", aliases: ["rode wijn", "huiswijn rood", "rood", "vin rouge", "red wine", "glas rode wijn"], abv: 13.0, vol: 150, cat: "wijn" },
  { name: "Rosé (glas)", aliases: ["rose", "rosé", "rose wijn", "vin rose"], abv: 12.0, vol: 150, cat: "wijn" },
  { name: "Witte wijn (fles)", aliases: ["fles witte wijn", "fles wit"], abv: 12.0, vol: 750, cat: "wijn" },
  { name: "Rode wijn (fles)", aliases: ["fles rode wijn", "fles rood"], abv: 13.0, vol: 750, cat: "wijn" },
  { name: "Cava", aliases: ["glas cava", "cava brut"], abv: 11.5, vol: 125, cat: "schuimwijn" },
  { name: "Prosecco", aliases: ["glas prosecco"], abv: 11.0, vol: 125, cat: "schuimwijn" },
  { name: "Champagne", aliases: ["glas champagne", "coupe champagne"], abv: 12.0, vol: 125, cat: "schuimwijn" },
  { name: "Cava (fles)", aliases: ["fles cava"], abv: 11.5, vol: 750, cat: "schuimwijn" },

  // ── Aperitieven & versterkte wijn ─────────────────────────────
  { name: "Porto", aliases: ["porto rood", "porto wit", "port"], abv: 19.5, vol: 80, cat: "aperitief" },
  { name: "Martini Bianco", aliases: ["martini", "martini wit"], abv: 15.0, vol: 80, cat: "aperitief" },
  { name: "Martini Rosso", aliases: ["martini rood"], abv: 15.0, vol: 80, cat: "aperitief" },
  { name: "Campari", aliases: [], abv: 25.0, vol: 50, cat: "aperitief" },
  { name: "Picon", aliases: ["picon vin blanc"], abv: 12.0, vol: 150, cat: "aperitief" },
  { name: "Pineau des Charentes", aliases: ["pineau"], abv: 17.0, vol: 80, cat: "aperitief" },
  { name: "Sherry", aliases: ["jerez"], abv: 17.5, vol: 80, cat: "aperitief" },
  { name: "Pastis", aliases: ["ricard", "pernod"], abv: 45.0, vol: 25, cat: "sterk" },

  // ── Sterke drank (standaard 4 cl shot/serve) ─────────────────
  { name: "Jenever", aliases: ["genever", "witte jenever", "jonge jenever", "oude jenever", "hasseltse jenever"], abv: 30.0, vol: 40, cat: "sterk" },
  { name: "Fruitjenever", aliases: ["appeljenever", "citroenjenever", "passoa jenever"], abv: 20.0, vol: 40, cat: "sterk" },
  { name: "Gin", aliases: ["dry gin"], abv: 40.0, vol: 40, cat: "sterk" },
  { name: "Vodka", aliases: ["wodka", "eristoff", "absolut", "smirnoff"], abv: 37.5, vol: 40, cat: "sterk" },
  { name: "Whisky", aliases: ["whiskey", "scotch", "bourbon", "jack daniels", "johnnie walker", "jameson", "j&b"], abv: 40.0, vol: 40, cat: "sterk" },
  { name: "Rum", aliases: ["bacardi", "havana club", "captain morgan", "bruine rum", "witte rum"], abv: 37.5, vol: 40, cat: "sterk" },
  { name: "Tequila", aliases: [], abv: 38.0, vol: 40, cat: "sterk" },
  { name: "Cognac", aliases: ["brandy", "remy martin", "hennessy"], abv: 40.0, vol: 40, cat: "sterk" },
  { name: "Calvados", aliases: [], abv: 40.0, vol: 40, cat: "sterk" },
  { name: "Grappa", aliases: [], abv: 40.0, vol: 40, cat: "sterk" },

  // ── Likeuren & shots ──────────────────────────────────────────
  { name: "Amaretto", aliases: ["disaronno"], abv: 28.0, vol: 40, cat: "likeur" },
  { name: "Baileys", aliases: ["baileys irish cream"], abv: 17.0, vol: 50, cat: "likeur" },
  { name: "Limoncello", aliases: [], abv: 28.0, vol: 40, cat: "likeur" },
  { name: "Sambuca", aliases: [], abv: 38.0, vol: 30, cat: "likeur" },
  { name: "Jägermeister", aliases: ["jagermeister", "jager"], abv: 35.0, vol: 30, cat: "likeur" },
  { name: "Cointreau", aliases: [], abv: 40.0, vol: 40, cat: "likeur" },
  { name: "Grand Marnier", aliases: [], abv: 40.0, vol: 40, cat: "likeur" },
  { name: "Passoa", aliases: [], abv: 17.0, vol: 50, cat: "likeur" },
  { name: "Pisang Ambon", aliases: ["pisang"], abv: 17.5, vol: 50, cat: "likeur" },
  { name: "Safari", aliases: [], abv: 20.0, vol: 50, cat: "likeur" },
  { name: "Mandarine Napoléon", aliases: ["mandarine napoleon"], abv: 38.0, vol: 40, cat: "likeur" },
  { name: "Elixir d'Anvers", aliases: ["elixir danvers"], abv: 37.0, vol: 40, cat: "likeur" },

  // ── Cocktails & longdrinks (abv = effectief % van het hele glas) ──
  { name: "Gin-tonic", aliases: ["gin tonic", "gintonic", "g&t"], abv: 8.0, vol: 300, cat: "cocktail" },
  { name: "Aperol Spritz", aliases: ["aperol", "spritz"], abv: 9.0, vol: 200, cat: "cocktail" },
  { name: "Limoncello Spritz", aliases: [], abv: 9.0, vol: 200, cat: "cocktail" },
  { name: "Hugo", aliases: ["hugo spritz"], abv: 7.0, vol: 200, cat: "cocktail" },
  { name: "Mojito", aliases: [], abv: 10.0, vol: 250, cat: "cocktail" },
  { name: "Caipirinha", aliases: [], abv: 18.0, vol: 150, cat: "cocktail" },
  { name: "Margarita", aliases: [], abv: 20.0, vol: 130, cat: "cocktail" },
  { name: "Cuba Libre", aliases: ["rum cola", "bacardi cola"], abv: 8.0, vol: 250, cat: "cocktail" },
  { name: "Vodka Red Bull", aliases: ["vodka redbull"], abv: 7.0, vol: 250, cat: "cocktail" },
  { name: "Piña Colada", aliases: ["pina colada"], abv: 10.0, vol: 250, cat: "cocktail" },
  { name: "Sex on the Beach", aliases: [], abv: 10.0, vol: 250, cat: "cocktail" },
  { name: "Cosmopolitan", aliases: ["cosmo"], abv: 20.0, vol: 130, cat: "cocktail" },
  { name: "Negroni", aliases: [], abv: 24.0, vol: 100, cat: "cocktail" },
  { name: "Old Fashioned", aliases: [], abv: 32.0, vol: 90, cat: "cocktail" },
  { name: "Espresso Martini", aliases: [], abv: 15.0, vol: 130, cat: "cocktail" },
  { name: "Dark 'n Stormy", aliases: ["dark and stormy"], abv: 9.0, vol: 250, cat: "cocktail" },
  { name: "Long Island Iced Tea", aliases: ["long island"], abv: 16.0, vol: 280, cat: "cocktail" },
  { name: "Tequila Sunrise", aliases: [], abv: 10.0, vol: 220, cat: "cocktail" },
  { name: "Mai Tai", aliases: [], abv: 17.0, vol: 180, cat: "cocktail" },
  { name: "Daiquiri", aliases: [], abv: 18.0, vol: 130, cat: "cocktail" },
  { name: "Moscow Mule", aliases: [], abv: 9.0, vol: 250, cat: "cocktail" },
  { name: "Kir", aliases: ["kir royal"], abv: 11.0, vol: 125, cat: "cocktail" },
  { name: "Sangria", aliases: ["glas sangria"], abv: 9.0, vol: 200, cat: "cocktail" },
];

// Fallback-schattingen op categorietrefwoord, voor dranken die niet in de database staan.
// volgorde is belangrijk: specifiekere trefwoorden eerst
const CATEGORY_FALLBACKS = [
  { kw: ["tripel", "triple", "trappist", "quadrupel", "quadruple", "grand cru"], abv: 8.5, vol: 330, cat: "bier" },
  { kw: ["dubbel", "double", "bruin bier", "donker bier", "amber"], abv: 6.8, vol: 330, cat: "bier" },
  { kw: ["ipa", "stout", "porter"], abv: 6.5, vol: 330, cat: "bier" },
  { kw: ["blond"], abv: 6.5, vol: 330, cat: "bier" },
  { kw: ["kriek", "fruitbier", "framboise"], abv: 3.5, vol: 250, cat: "bier" },
  { kw: ["witbier", "weizen", "wit bier", "blanche"], abv: 5.0, vol: 250, cat: "bier" },
  { kw: ["pils", "pilsener", "lager", "bier", "beer", "biere", "bière"], abv: 5.2, vol: 250, cat: "bier" },
  { kw: ["cava", "prosecco", "champagne", "cremant", "crémant", "bubbels", "schuimwijn", "sekt"], abv: 11.5, vol: 125, cat: "schuimwijn" },
  { kw: ["porto", "port", "sherry", "vermout", "vermouth", "pineau"], abv: 18.0, vol: 80, cat: "aperitief" },
  { kw: ["wijn", "wine", "vin", "chardonnay", "sauvignon", "merlot", "pinot", "riesling", "rioja", "malbec", "syrah", "cabernet", "rosé", "rose"], abv: 12.5, vol: 150, cat: "wijn" },
  { kw: ["spritz"], abv: 9.0, vol: 200, cat: "cocktail" },
  { kw: ["cocktail", "mocktail- niet", "longdrink"], abv: 12.0, vol: 200, cat: "cocktail" },
  { kw: ["jenever", "genever"], abv: 30.0, vol: 40, cat: "sterk" },
  { kw: ["gin", "vodka", "wodka", "whisky", "whiskey", "rum", "tequila", "cognac", "brandy", "armagnac", "calvados", "grappa", "eau de vie"], abv: 40.0, vol: 40, cat: "sterk" },
  { kw: ["likeur", "liqueur", "shot", "shooter"], abv: 25.0, vol: 40, cat: "likeur" },
  { kw: ["cider", "cidre"], abv: 4.5, vol: 330, cat: "bier" },
];

// Niet-alcoholische trefwoorden: regels hiermee worden overgeslagen
const NON_ALCOHOL_KEYWORDS = [
  "cola", "coca", "fanta", "sprite", "ice tea", "icetea", "fristi", "cecemel",
  "koffie", "coffee", "espresso", "cappuccino", "latte", "thee", "tea",
  "water", "spa", "chaudfontaine", "bru ", "tonic", "limonade", "fruitsap",
  "appelsap", "sinaasappelsap", "jus d", "smoothie", "milkshake", "chocomelk",
  "warme choco", "soep", "0.0", "0,0", "alcoholvrij", "alcoholvrije", "zonder alcohol",
  "sportzot", "tourtel", "spuitwater", "plat water", "bruiswater", "red bull",
  "nalu", "aquarius", "schweppes", "gini", "looza", "minute maid", "oasis",
];

if (typeof module !== "undefined") {
  module.exports = { DRINKS_DB, CATEGORY_FALLBACKS, NON_ALCOHOL_KEYWORDS };
} else {
  // top-level const hangt niet aan window — expliciet exporteren voor parser.js
  globalThis.DRINKS_DB = DRINKS_DB;
  globalThis.CATEGORY_FALLBACKS = CATEGORY_FALLBACKS;
  globalThis.NON_ALCOHOL_KEYWORDS = NON_ALCOHOL_KEYWORDS;
}
